"""
MediSimplify core package initialization and configuration utilities.
"""
import os
import re
from dotenv import load_dotenv
from openai import OpenAI


def get_client() -> OpenAI:
    """Initializes and returns an OpenAI-compatible SDK client."""
    load_dotenv(override=True)
    api_key = os.environ.get("OPENAI_API_KEY") or os.environ.get("GEMINI_API_KEY")
    base_url = os.environ.get("OPENAI_BASE_URL") or None
    return OpenAI(api_key=api_key, base_url=base_url)


def get_model() -> str:
    """Retrieves the configured LLM model identifier."""
    load_dotenv(override=True)
    return os.environ.get("MODEL_NAME") or os.environ.get("OPENAI_MODEL") or "gpt-4o-mini"


def clean_json_text(text: str) -> str:
    """Strips markdown code fences, whitespace, and fixes invalid JSON backslash escapes from raw LLM responses."""
    text = text.strip()
    if text.startswith("```"):
        lines = text.splitlines()
        if lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip().startswith("```"):
            lines = lines[:-1]
        text = "\n".join(lines).strip()
    
    # Fix invalid JSON backslash escapes generated by LLMs (e.g. \o, \p, \units, LaTeX symbols, medical notes)
    text = re.sub(r'(?<!\\)\\(?![\\/bfnrt"]|u[0-9a-fA-F]{4})', r'\\\\', text)
    return text
